# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20170113_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='chords',
            new_name='tabs_and_chords',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='tabs',
            new_name='tags',
        ),
    ]
