# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_auto_20170117_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=100),
        ),
    ]
